global:
  scrape_interval: 15s # Raspa cada 15 segundos

scrape_configs:
  - job_name: 'nginx'
    # Añadir esto para permitir Prometeo raspar los propios puntos finales de Prometeo
    # static_configs:
    #   - targets: ['localhost:9090']
    # Si estás en la misma red de Docker, puedes apuntar directamente al nombre del servicio Nginx
    # Aquí asumimos que Nginx está en una red separada para el streaming,
    # así que rascaremos el Nginx a través del Node Exporter
    metrics_path: /metrics # La ruta por defecto para Node Exporter y Nginx Exporter
    static_configs:
      - targets: ['nginx-exporter:9113'] # El 'nginx-exporter' es el nombre del servicio Docker (ver docker-compose.yml)
        labels:
          instance: nginx_stream_server

  # Opcional: Para monitorear el propio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Opcional: Para monitorear el Node Exporter (métricas del SO del contenedor)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100'] # Nombre del servicio Node Exporter